### PR TITLE
V2 — ES, new API, metrics-only

### LINKED ISSUE #11: Changes to Chrome TextBaseline coming
Hi, just a heads up that Chrome's interpretation of text baseline has just changed to match FF i.e. what was filed as a [FF bug](https://bugzilla.mozilla.org/show_bug.cgi?id=737852) is actually inline with the spec, and Chrome have [dropped in a fix](https://bugs.chromium.org/p/chromium/issues/detail?id=607053) to align to this.

So the line at https://github.com/mapbox/tiny-sdf/blob/master/index.js#L34 may not work with a future Chrome release.

### LINKED ISSUE #17: Modernize, switch to ES6 / Modules

### LINKED ISSUE #25: V2 changes
Let's record any API-breaking features we'd like to do so that we can do them all at once in a semver-major bump v2.

- Modernize the library for ES6 syntax + ES Modules. #17 At this point we can completely drop the CommonJS entry point because Node v10 approaches End of Life and Node v12 fully supports ESM.
- Instead of distinct `draw` and `drawWithMetrics` methods, switch to a single method that always does metrics and trimming. The bbox metrics are now universally supported (everything except IE11), and we don't have to worry about backwards-compatibility too much if we're doing a semver-major bump.
- As pointed out in https://github.com/mapbox/tiny-sdf/issues/17#issuecomment-519513384, it would be nice to get rid of long lists of arguments in the constructor, and use a named options approach in the API.

Anything else @ChrisLoer?

### PR DESCRIPTION
**Pull request by mourner**
Closes #25. Closes #23. Closes #17. Closes #11.

- [x] Switch to ES syntax
- [x] Remove non-metrics code pathway
- [x] Add a method to get metrics prior to drawing
- [x] Switch from CommonJS to ESM
- [x] Change API to accept an options object
- [x] Preferably add some tests & set up Travis
- [x] Streamline the return API
- [x] Update Readme

Commits are self-contained — let's merge with rebase. The massive `package-lock.json` changes are due to a newer format used by `npm v7`.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,171 +1,126 @@
...
+        radius = 8,
+        cutoff = 0.25,
+        fontFamily = 'sans-serif',
+        fontWeight = 'normal'
+    }) {
+        this.buffer = buffer;
+        this.cutoff = cutoff;
+        this.radius = radius;
+
+        // For backwards compatibility, we honor the implicit contract that the
```
Comment (ChrisLoer) [inline index.js:16]: Since we don't have the backwards compatibility constraints here, I think we can simplify things a little by just making the canvas bigger:

- Don't need to track a separate `gridSize`
- Don't need to have clipping logic in `getMetrics` (it might still be necessary to handle as an edge case, but it might be simpler to just start with a larger canvas and in the unlikely case that you'd overflow, just resize the canvas to be bigger).

File: index.js [hunk 2]
```diff
@@ -1,171 +1,126 @@
...
-            } else {
-                var b = Math.max(0, 0.5 - a);
-                var c = Math.max(0, a - 0.5);
-                gridOuter[j] = b * b;
-                gridInner[j] = c * c;
-            }
-        }
-    }
-}
+        const sdfWidth = width + 2 * this.buffer;
```
Comment (ChrisLoer) [inline index.js:66]: It feels a little clunky that we return both a "width" and an "sdfWidth" that are just different by a constant. There were two reasons I introduced it:

- At first, `sdfWidth` and `width` could be different in some clipping cases (this is no longer true).
- It's weird to make the caller responsible for knowing the right conversion from width -> sdfWidth. (e.g. during development I would accidentally mismatch them and find out when `AlphaImage.copy` threw an exception).

The first concern isn't an issue any more. I wonder if there's a better way to handle the second. One option would be to just use the SDF/bitmap width for the metrics as well. The only place I know it's used in GL JS is to do center-alignment for vertical labels, which would still work with a constant offset but would be shifted a pixel or two. If TinySDF were part of GL JS, I'd just say "it should return an `AlphaImage`", but we probably don't want that dependency...

File: test/test.js [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+        actualImg[4 * i + 3] = 255;
+    }
+
+    if (process.env.UPDATE) {
+        const png = new PNG({width, height});
+        png.data.set(actualImg);
+        writeFileSync(new URL('./glyph.png', import.meta.url), PNG.sync.write(png));
+    }
+
+    const numDiffPixels = pixelmatch(fixtureA.data, actualImg, undefined, width, height);
```
Comment (ChrisLoer) [inline test/test.js:47]: This test fails on my system, with 1008 different pixels, presumably because different fonts are installed. I think what you might need to do for this test is stub out the canvas fillText operation with something that copies in a stub glyph. Actually modifying the installed system fonts before running the test is way too tricky, and I don't know of another way to change what the canvas will use.

File: README.md [hunk 4]
```diff
@@ -10,31 +10,29 @@ This implementation is based directly on the algorithm published in the Felzensz
 Demo: http://mapbox.github.io/tiny-sdf/
 
 ## Usage
+
```
Comment (ChrisLoer) [inline README.md:13]: Could the README have a little setup section? Maybe:

- Showing travis badge
- Listing node version dependency (I happened to be on node v10 the first time I tried `npm test` and got an unfriendly "unexpected identified" error from the "import TinySDF" line)
- Pointing to `npm install` and `npm test`

File: index.js [hunk 5]
```diff
@@ -1,171 +1,117 @@
...
+        gridInner.fill(0, 0, width * height);
 
-    prepareGrids(imgData, width, height, glyphWidth, glyphHeight, this.gridOuter, this.gridInner);
+        const offset = (width - glyphWidth) >> 1;
 
-    edt(this.gridOuter, width, height, this.f, this.v, this.z);
-    edt(this.gridInner, width, height, this.f, this.v, this.z);
+        for (let y = 0; y < glyphHeight; y++) {
+            for (let x = 0; x < glyphWidth; x++) {
+                const j = (y + offset) * width + x + offset;
```
Comment (ChrisLoer) [inline index.js:87]: Did you go back to the original grid preparation code here mainly because it's more compact? I made the changes after experimenting, just reasoning that since it was such a tight loop small things could make a difference. But the idea was (1) half the number of branch instructions, and (2) simple multiplication may be cheaper than `Math.pow`. My benchmarking strategy was to profile a glyph-heavy load where TinySDF took about 500ms and look specifically at the time spent in prepareGrids. It ended up looking like a 15ms->10ms change over several runs. So pretty small and maybe not worthwhile overall. I can try running again to get the numbers documented.

**Review by ChrisLoer — COMMENTED** [review]
This is looking really good! I think the test is the only big thing outstanding that needs to change.

File: index.html [hunk 6]
```diff
@@ -63,10 +63,10 @@ <h1><a href="https://github.com/mapbox/tiny-sdf">TinySDF</a> demo</h1>
 }
 </script>
 
-<script>module = {};</script>
-<script src="https://cdnjs.cloudflare.com/ajax/libs/gl-matrix/2.3.2/gl-matrix-min.js"></script>
-<script src="index.js"></script>
-<script>
+<script type="module">
```
[the remark this answers is not in the document]
Comment (mourner) [reply index.html:66]: Yeah, unfortunately there's no way around it. The current setup that allowed locally loading the CommonJS module was a huge hack. So I have to get used to launching a local static server when working on my libraries. Thankfully it's relatively easy — `npx st -nc` in the directory with the minimal server I'm using.

File: test/test.js (hunk 3 above)
Comment (mourner) [reply test/test.js:47]: Yeah, I tried a lot of different fonts and Travis configs until I settled on this one that passed both on my local MBP and on Travis (OSX image) at the same time, but you're probably right that it's fragile and mocking the canvas with a pre-drawn fixture is better. Might be a pain to update but will work in any environment and avoid the heavy `canvas` dependency.

File: index.js (hunk 5 above)
Comment (mourner) [reply index.js:87]: @ChrisLoer yeah, in my tests it didn't make much difference and made the code a lot more verbose, but I can backtrack on this now that the overall code is smaller.

File: index.html (hunk 6 above)
[the remark this answers is not in the document]
Comment (ChrisLoer) [reply index.html:66]: 👍 

Would it make sense to add something like:

```
{
  "devDependencies": {
    "st": "^2.0.0"
  },
  "scripts": {
    "start-server": "st --no-cache --localhost --port 9966 --index index.html ."
  }
}
```

As a way of kind of hinting to developers "here's an easy way to look at it"?

**Comment by mourner** [comment]
@ChrisLoer updated the testing approach so that it mocks `fillText` and `measureText` so now the tests are deterministic regardless of font or OS. The fixtures are updated with `UPDATE=true node test/test.js`. Merging this now but will follow up with README & scripts updates separately.
